# Generated by Django 4.1.5 on 2023-03-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_standardize_description_comments'),
        ('netbox_project_quota', '0002_remove_project_devices_remove_project_ipaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact',
            field=models.ManyToManyField(blank=True, default=None, related_name='assigned_contact', to='tenancy.contact'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectDevice',
        ),
    ]
