# Generated by Django 4.1.5 on 2023-03-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_project_quota', '0004_remove_project_domain_name_project_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotatemplate',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
